<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- ONLY keep general-purpose libraries if absolutely needed -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartMenuOptim.Domain\SmartMenuOptim.Domain.csproj" />
    <ProjectReference Include="..\SmartMenuOptim.Infrastructure\SmartMenuOptim.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartMenuOptim.Shared\SmartMenuOptim.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Behaviors\" />
    <Folder Include="CQRS\Commands\" />
    <Folder Include="Handlers\" />
    <Folder Include="Mappings\" />
    <Folder Include="CQRS\" />
    <Folder Include="CQRS\Queries\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
