// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartMenuOptim.Shared.Data.Context;

#nullable disable

namespace SmartMenuOptim.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030231833_AddMultitenantSupport")]
    partial class AddMultitenantSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerLoyalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LifetimePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RestaurantId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerLoyalties_Restaurant_Customer_Unique");

                    b.HasIndex("RestaurantId", "CustomerId", "Points")
                        .HasDatabaseName("IX_CustomerLoyalty_Restaurant_Customer_Points");

                    b.HasIndex("RestaurantId", "Tier", "LastActivity")
                        .HasDatabaseName("IX_CustomerLoyalty_Restaurant_Tier_Activity");

                    b.ToTable("CustomerLoyalties");
                });

            modelBuilder.Entity("Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("AvailableFrom")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("AvailableTo")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("MenuTypeId");

                    b.HasIndex("RestaurantId", "AvailableFrom", "AvailableTo")
                        .HasDatabaseName("IX_Menus_Restaurant_Availability");

                    b.HasIndex("RestaurantId", "IsActive", "AvailableFrom", "AvailableTo")
                        .HasDatabaseName("IX_Menus_Restaurant_Availability_Active");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("MenuDishes", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("RestaurantId");

                    b.HasKey("MenuId", "DishId");

                    b.HasIndex("DishId", "MenuId")
                        .HasDatabaseName("IX_MenuDishes_Dish_Menu");

                    b.HasIndex("RestaurantId", "MenuId", "DishId")
                        .HasDatabaseName("IX_MenuDishes_Restaurant_Menu_Dish");

                    b.ToTable("MenuDishes", (string)null);
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PremiumCustomerReviewCountThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("RegularCustomerReviewCountThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewCountThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("SalesThreshold")
                        .HasColumnType("integer");

                    b.Property<double>("SentimentThreshold")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WellSoldThreshold")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_AdminUsers_Email");

                    b.HasIndex("Email", "Username")
                        .IsUnique()
                        .HasDatabaseName("IX_AdminUsers_Email_Username_Unique");

                    b.HasIndex("PhoneNumber", "LastLoginAt")
                        .HasDatabaseName("IX_AdminUsers_Phone_LastLogin");

                    b.HasIndex("Role", "IsActive")
                        .HasDatabaseName("IX_AdminUsers_Role_Status");

                    b.HasIndex("Username", "IsActive")
                        .HasDatabaseName("IX_Customers_Username_Active");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.BusinessRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("IX_BusinessRules_AdminUserId");

                    b.HasIndex("RuleType", "CreatedAt")
                        .HasDatabaseName("IX_BusinessRules_RuleType_CreatedAt");

                    b.HasIndex(new[] { "RuleType", "AdminUserId", "CreatedAt" }, "IX_BusinessRules_RuleType_AdminUser_Date");

                    b.ToTable("BusinessRules");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptsMarketing")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DateRegistered")
                        .HasDatabaseName("IX_Customers_DateRegistered");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Customers_Email");

                    b.HasIndex("LastActivityDate", "IsActive")
                        .HasDatabaseName("IX_Customers_Activity_Status");

                    b.HasIndex("Name", "IsActive")
                        .HasDatabaseName("IX_Customers_Name_Status");

                    b.HasIndex("Username", "IsActive")
                        .HasDatabaseName("IX_Customers_Username_Status");

                    b.HasIndex(new[] { "Email", "Username" }, "IX_Customers_Email_Username_Unique")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber", "PhoneNumberConfirmed" }, "IX_Customers_Phone_Verified");

                    b.HasIndex(new[] { "DateRegistered", "LastActivityDate" }, "IX_Customers_Registered_Activity");

                    b.HasIndex(new[] { "Username", "IsActive" }, "IX_Customers_Username_Active")
                        .HasDatabaseName("IX_Customers_Username_Active1");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_StaffMembers_Email");

                    b.HasIndex(new[] { "Username", "IsActive" }, "IX_Customers_Username_Active")
                        .HasDatabaseName("IX_Customers_Username_Active2");

                    b.HasIndex(new[] { "Email" }, "IX_StaffMembers_Email_Unique")
                        .IsUnique();

                    b.HasIndex(new[] { "Email", "Username" }, "IX_StaffMembers_Email_Username_Unique")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber", "PhoneNumberConfirmed" }, "IX_StaffMembers_Phone_Verified");

                    b.HasIndex(new[] { "RestaurantId", "Role" }, "IX_StaffMembers_Restaurant_Role");

                    b.HasIndex(new[] { "RestaurantId", "Role", "EmploymentStatus", "IsActive" }, "IX_StaffMembers_Restaurant_Role_Status");

                    b.HasIndex(new[] { "Username" }, "IX_StaffMembers_Username_Unique")
                        .IsUnique();

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_Restaurant_UniqueName");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DishPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Dishes_CategoryId");

                    b.HasIndex("RestaurantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Dishes_Restaurant_UniqueName");

                    b.HasIndex("RestaurantId", "CategoryId", "DishPrice")
                        .HasDatabaseName("IX_Dishes_Restaurant_Category_Price");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerLoyaltyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsChange")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("CustomerLoyaltyId", "CreatedAt")
                        .HasDatabaseName("IX_LoyaltyTransactions_CustomerLoyalty_CreatedAt");

                    b.HasIndex("RestaurantId", "CustomerLoyaltyId", "CreatedAt")
                        .HasDatabaseName("IX_LoyaltyTransactions_Restaurant_CustomerLoyalty_Date");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.MenuType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("DefaultEndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("DefaultStartTime")
                        .HasColumnType("interval");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_MenuTypes_Restaurant_UniqueName");

                    b.HasIndex("RestaurantId", "IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_MenuTypes_Restaurant_Active_Order");

                    b.ToTable("MenuTypes");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("HandledByStaffId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("HandledByStaffId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("CustomerId", "CreatedAt")
                        .HasDatabaseName("IX_Orders_Customer_CreatedAt");

                    b.HasIndex("RestaurantId", "CreatedAt")
                        .HasDatabaseName("IX_Orders_Restaurant_CreatedAt");

                    b.HasIndex("RestaurantId", "HandledByStaffId", "OrderDate")
                        .HasDatabaseName("IX_Orders_Restaurant_Staff_Date");

                    b.HasIndex("RestaurantId", "OrderStatusId", "CreatedAt")
                        .HasDatabaseName("IX_Orders_Restaurant_Status_Created");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItems_OrderId");

                    b.HasIndex("DishId", "CreatedAt")
                        .HasDatabaseName("IX_OrderItems_Dish_CreatedAt");

                    b.HasIndex("RestaurantId", "OrderId")
                        .HasDatabaseName("IX_OrderItems_Restaurant_Order");

                    b.HasIndex("RestaurantId", "DishId", "CreatedAt")
                        .HasDatabaseName("IX_OrderItems_Restaurant_Dish_CreatedAt");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "Name")
                        .HasDatabaseName("IX_OrderStatuses_Restaurant_Name");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "IsActive", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_Promotions_Restaurant_Active_Dates");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RestaurantId", "ReservationTime")
                        .HasDatabaseName("IX_Reservations_Restaurant_Time");

                    b.HasIndex("TableId", "ReservationTime")
                        .HasDatabaseName("IX_Reservations_Table_Time");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Restaurants_OwnerId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<double>("SentimentScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DishId", "CreatedAt")
                        .HasDatabaseName("IX_Reviews_Dish_CreatedAt");

                    b.HasIndex("RestaurantId", "CreatedAt")
                        .HasDatabaseName("IX_Reviews_Restaurant_CreatedAt");

                    b.HasIndex("RestaurantId", "Rating", "CreatedAt")
                        .HasDatabaseName("IX_Reviews_Restaurant_Rating_Date");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.SaleRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("RestaurantId", "DishId", "SaleDate")
                        .HasDatabaseName("IX_SaleRecords_Restaurant_Dish_Date");

                    b.ToTable("SaleRecords");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.StaffSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByAdminUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByStaffId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedByAdminUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("integer");

                    b.Property<int?>("LastModifiedByStaffId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RecurringDay")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StaffMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminUserId")
                        .HasDatabaseName("IX_StaffSchedules_CreatedByAdminUserId");

                    b.HasIndex("CreatedByStaffId")
                        .HasDatabaseName("IX_StaffSchedules_CreatedByStaffId");

                    b.HasIndex("LastModifiedByAdminUserId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("StaffMemberId");

                    b.HasIndex("RestaurantId", "ShiftStart", "ShiftEnd")
                        .HasDatabaseName("IX_StaffSchedules_Restaurant_ShiftRange");

                    b.HasIndex("RestaurantId", "StaffMemberId", "ShiftStart")
                        .HasDatabaseName("IX_StaffSchedules_Restaurant_Staff_ShiftStart");

                    b.ToTable("StaffSchedules");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "IsAvailable", "Capacity")
                        .HasDatabaseName("IX_Tables_Restaurant_Availability_Capacity");

                    b.ToTable("RestaurantTables", (string)null);
                });

            modelBuilder.Entity("CustomerLoyalty", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.Customer", "Customer")
                        .WithMany("CustomerLoyalties")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("CustomerLoyalties")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Menu", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.MenuType", "MenuType")
                        .WithMany("Menus")
                        .HasForeignKey("MenuTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("Menus")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuType");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("MenuDishes", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Dish", null)
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.BusinessRule", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.AdminUser", "AdminUser")
                        .WithMany("BusinessRules")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.StaffMember", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Category", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Dish", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("Dishes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.LoyaltyTransaction", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerLoyalty", "CustomerLoyalty")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerLoyaltyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerLoyalty");

                    b.Navigation("Order");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.MenuType", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("MenuTypes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Order", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.StaffMember", "HandledBy")
                        .WithMany("HandledOrders")
                        .HasForeignKey("HandledByStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("HandledBy");

                    b.Navigation("Restaurant");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.OrderItem", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Dish", "Dish")
                        .WithMany("OrderItems")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Order");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.OrderStatus", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("OrderStatuses")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Promotion", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("Promotions")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Reservation", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Restaurant");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.AdminUser", "Owner")
                        .WithMany("OwnedRestaurants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Review", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Dish", "Dish")
                        .WithMany("Reviews")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Dish");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.SaleRecord", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Dish", "Dish")
                        .WithMany("SaleRecords")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("SaleRecords")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.StaffSchedule", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.AdminUser", "CreatedByAdminUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminUserId");

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.StaffMember", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.AdminUser", "LastModifiedByAdminUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByAdminUserId");

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.StaffMember", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("StaffSchedules")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.StaffMember", "StaffMember")
                        .WithMany("Schedules")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("CreatedByAdminUser");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("LastModifiedByAdminUser");

                    b.Navigation("Restaurant");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Table", b =>
                {
                    b.HasOne("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", "Restaurant")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("CustomerLoyalty", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.AdminUser", b =>
                {
                    b.Navigation("BusinessRules");

                    b.Navigation("OwnedRestaurants");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.Customer", b =>
                {
                    b.Navigation("CustomerLoyalties");

                    b.Navigation("Orders");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.GlobalEntities.StaffMember", b =>
                {
                    b.Navigation("HandledOrders");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Dish", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("SaleRecords");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.MenuType", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Restaurant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CustomerLoyalties");

                    b.Navigation("Dishes");

                    b.Navigation("MenuTypes");

                    b.Navigation("Menus");

                    b.Navigation("OrderStatuses");

                    b.Navigation("Orders");

                    b.Navigation("Promotions");

                    b.Navigation("Reviews");

                    b.Navigation("SaleRecords");

                    b.Navigation("StaffSchedules");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("SmartMenuOptim.Shared.Data.Entities.TenantSpecificEntities.Table", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
