using SmartMenuOptim.Domain.Common;

namespace SmartMenuOptim.Domain.Events.SaleEvents;

/// <summary>
/// Domain event raised when daily sales are summarized for a restaurant.
/// This event aggregates individual sale records into daily summaries for reporting and analytics.
/// </summary>
/// <remarks>
/// <para><strong>Event Trigger:</strong></para>
/// <para>This event is typically raised by a scheduled job at the end of each business day,
/// or when explicitly triggered by management for reporting purposes.</para>
/// 
/// <para><strong>Typical Event Handlers:</strong></para>
/// <list type="bullet">
///     <item><description><strong>ReportingHandler:</strong> Generates daily sales reports</description></item>
///     <item><description><strong>DashboardHandler:</strong> Updates management dashboards</description></item>
///     <item><description><strong>ComparisonHandler:</strong> Compares against historical data and targets</description></item>
///     <item><description><strong>AlertHandler:</strong> Triggers alerts for unusual patterns</description></item>
///     <item><description><strong>ForecastHandler:</strong> Updates demand forecasting models</description></item>
///     <item><description><strong>AccountingHandler:</strong> Prepares data for accounting systems</description></item>
///     <item><description><strong>AIInsightsHandler:</strong> Generates AI-powered insights and recommendations</description></item>
/// </list>
/// 
/// <para><strong>Analytics Insights:</strong></para>
/// <para>This summary event enables:</para>
/// <list type="bullet">
///     <item><description>Day-over-day comparison</description></item>
///     <item><description>Week-over-week trends</description></item>
///     <item><description>Seasonal pattern identification</description></item>
///     <item><description>Performance against targets</description></item>
///     <item><description>Peak hours analysis</description></item>
///     <item><description>Category performance breakdown</description></item>
/// </list>
/// 
/// <para><strong>AI Integration:</strong></para>
/// <para>The summarized data feeds into SmartMenuOptimizer's AI engine for:</para>
/// <list type="bullet">
///     <item><description>Menu optimization recommendations</description></item>
///     <item><description>Pricing suggestions</description></item>
///     <item><description>Staffing recommendations based on predicted traffic</description></item>
///     <item><description>Inventory optimization</description></item>
/// </list>
/// </remarks>
public sealed class DailySalesSummarizedEvent : DomainEventBase
{
    /// <summary>
    /// Gets the restaurant (tenant) identifier.
    /// </summary>
    public int RestaurantId { get; init; }

    /// <summary>
    /// Gets the restaurant name.
    /// </summary>
    public string RestaurantName { get; init; } = string.Empty;

    /// <summary>
    /// Gets the date being summarized.
    /// </summary>
    public DateOnly SummaryDate { get; init; }

    /// <summary>
    /// Gets the day of week for the summary.
    /// </summary>
    public DayOfWeek DayOfWeek => SummaryDate.DayOfWeek;

    /// <summary>
    /// Gets the total revenue for the day.
    /// </summary>
    public decimal TotalRevenue { get; init; }

    /// <summary>
    /// Gets the currency code.
    /// </summary>
    public string CurrencyCode { get; init; } = "USD";

    /// <summary>
    /// Gets the total number of orders.
    /// </summary>
    public int TotalOrders { get; init; }

    /// <summary>
    /// Gets the total number of items sold.
    /// </summary>
    public int TotalItemsSold { get; init; }

    /// <summary>
    /// Gets the average order value.
    /// </summary>
    public decimal AverageOrderValue => TotalOrders > 0 ? TotalRevenue / TotalOrders : 0;

    /// <summary>
    /// Gets the number of unique customers.
    /// </summary>
    public int UniqueCustomers { get; init; }

    /// <summary>
    /// Gets the top selling dish of the day.
    /// </summary>
    public string? TopSellingDish { get; init; }

    /// <summary>
    /// Gets the quantity of the top selling dish.
    /// </summary>
    public int TopSellingDishQuantity { get; init; }

    /// <summary>
    /// Gets the revenue generated by the top selling dish.
    /// </summary>
    public decimal TopSellingDishRevenue { get; init; }

    /// <summary>
    /// Gets the peak hour of the day (0-23).
    /// </summary>
    public int PeakHour { get; init; }

    /// <summary>
    /// Gets the number of orders during peak hour.
    /// </summary>
    public int PeakHourOrders { get; init; }

    /// <summary>
    /// Gets revenue breakdown by category.
    /// </summary>
    public Dictionary<string, decimal> RevenueByCategory { get; init; } = new();

    /// <summary>
    /// Gets order count breakdown by order type.
    /// </summary>
    public Dictionary<string, int> OrdersByType { get; init; } = new();

    /// <summary>
    /// Gets the total discount amount given.
    /// </summary>
    public decimal TotalDiscounts { get; init; }

    /// <summary>
    /// Gets the total tip amount (if applicable).
    /// </summary>
    public decimal TotalTips { get; init; }

    /// <summary>
    /// Gets the number of cancelled orders.
    /// </summary>
    public int CancelledOrders { get; init; }

    /// <summary>
    /// Gets the revenue lost to cancellations.
    /// </summary>
    public decimal CancellationRevenueLost { get; init; }

    /// <summary>
    /// Gets comparison to previous day's revenue.
    /// </summary>
    public decimal? PreviousDayRevenue { get; init; }

    /// <summary>
    /// Gets the percentage change from previous day.
    /// </summary>
    public decimal? PercentChangeFromPreviousDay => 
        PreviousDayRevenue.HasValue && PreviousDayRevenue.Value > 0 
            ? ((TotalRevenue - PreviousDayRevenue.Value) / PreviousDayRevenue.Value) * 100 
            : null;

    /// <summary>
    /// Gets comparison to same day last week.
    /// </summary>
    public decimal? SameDayLastWeekRevenue { get; init; }

    /// <summary>
    /// Gets the percentage change from same day last week.
    /// </summary>
    public decimal? PercentChangeFromLastWeek =>
        SameDayLastWeekRevenue.HasValue && SameDayLastWeekRevenue.Value > 0
            ? ((TotalRevenue - SameDayLastWeekRevenue.Value) / SameDayLastWeekRevenue.Value) * 100
            : null;

    /// <summary>
    /// Gets the daily target revenue (if set).
    /// </summary>
    public decimal? DailyTarget { get; init; }

    /// <summary>
    /// Gets the percentage of daily target achieved.
    /// </summary>
    public decimal? TargetAchievementPercent =>
        DailyTarget.HasValue && DailyTarget.Value > 0
            ? (TotalRevenue / DailyTarget.Value) * 100
            : null;

    /// <summary>
    /// Gets any underperforming dishes identified (sold below threshold).
    /// </summary>
    public List<string> UnderperformingDishes { get; init; } = new();

    /// <summary>
    /// Gets new customers acquired today.
    /// </summary>
    public int NewCustomersAcquired { get; init; }

    /// <summary>
    /// Gets loyalty points awarded today.
    /// </summary>
    public int TotalLoyaltyPointsAwarded { get; init; }

    /// <summary>
    /// Initializes a new instance of the <see cref="DailySalesSummarizedEvent"/> class.
    /// </summary>
    public DailySalesSummarizedEvent(
        int restaurantId,
        string restaurantName,
        DateOnly summaryDate,
        decimal totalRevenue,
        int totalOrders,
        int totalItemsSold,
        int uniqueCustomers,
        string currencyCode = "USD",
        string? topSellingDish = null,
        int topSellingDishQuantity = 0,
        decimal topSellingDishRevenue = 0,
        int peakHour = 0,
        int peakHourOrders = 0,
        Dictionary<string, decimal>? revenueByCategory = null,
        Dictionary<string, int>? ordersByType = null,
        decimal totalDiscounts = 0,
        decimal totalTips = 0,
        int cancelledOrders = 0,
        decimal cancellationRevenueLost = 0,
        decimal? previousDayRevenue = null,
        decimal? sameDayLastWeekRevenue = null,
        decimal? dailyTarget = null,
        List<string>? underperformingDishes = null,
        int newCustomersAcquired = 0,
        int totalLoyaltyPointsAwarded = 0)
    {
        RestaurantId = restaurantId;
        RestaurantName = restaurantName;
        SummaryDate = summaryDate;
        TotalRevenue = totalRevenue;
        CurrencyCode = currencyCode;
        TotalOrders = totalOrders;
        TotalItemsSold = totalItemsSold;
        UniqueCustomers = uniqueCustomers;
        TopSellingDish = topSellingDish;
        TopSellingDishQuantity = topSellingDishQuantity;
        TopSellingDishRevenue = topSellingDishRevenue;
        PeakHour = peakHour;
        PeakHourOrders = peakHourOrders;
        RevenueByCategory = revenueByCategory ?? new Dictionary<string, decimal>();
        OrdersByType = ordersByType ?? new Dictionary<string, int>();
        TotalDiscounts = totalDiscounts;
        TotalTips = totalTips;
        CancelledOrders = cancelledOrders;
        CancellationRevenueLost = cancellationRevenueLost;
        PreviousDayRevenue = previousDayRevenue;
        SameDayLastWeekRevenue = sameDayLastWeekRevenue;
        DailyTarget = dailyTarget;
        UnderperformingDishes = underperformingDishes ?? new List<string>();
        NewCustomersAcquired = newCustomersAcquired;
        TotalLoyaltyPointsAwarded = totalLoyaltyPointsAwarded;
    }

    /// <summary>
    /// Private parameterless constructor for serialization support.
    /// </summary>
    private DailySalesSummarizedEvent() { }
}
