namespace SmartMenuOptim.Domain.Aggregates.RestaurantAggregate;

/// <summary>
/// Operating hours configuration for a specific day of the week.
/// Child entity of Restaurant aggregate - semi-mutable configuration data.
/// </summary>
/// <remarks>
/// 🧩 CHILD ENTITY - Restaurant Aggregate (Tier 1)
/// 
/// Key Characteristics:
/// • Semi-mutable: Can update hours via Restaurant.SetBusinessHours()
/// • Created only via Restaurant aggregate methods
/// • Internal constructor prevents external instantiation
/// • Has Id for EF Core entity tracking (not a value object)
/// 
/// Business Rules:
/// • CloseTime must be after OpenTime
/// • IsClosed property when OpenTime == CloseTime
/// 
/// <code>
/// // ✅ CORRECT - Through parent aggregate
/// restaurant.SetBusinessHours(DayOfWeek.Monday, TimeSpan.FromHours(9), TimeSpan.FromHours(17));
/// 
/// // ❌ WRONG - Direct instantiation
/// var hours = new BusinessHours(...); // Should only be called by Restaurant
/// </code>
/// </remarks>
public class BusinessHours
{
    /// <summary>
    /// Unique identifier for this business hours record.
    /// </summary>
    /// <remarks>
    /// PRIMARY KEY: Required for EF Core entity tracking and database persistence.
    /// Auto-generated by the database when the record is first saved.
    /// </remarks>
    public int Id { get; private set; }
    
    /// <summary>
    /// Foreign key to the parent Restaurant.
    /// </summary>
    /// <remarks>
    /// AGGREGATE RELATIONSHIP: Links this child entity to its parent Restaurant aggregate root.
    /// Required for proper aggregate boundary enforcement and data integrity.
    /// </remarks>
    public int RestaurantId { get; private set; }
    
    /// <summary>
    /// The day of the week these hours apply to.
    /// </summary>
    public DayOfWeek DayOfWeek { get; private set; }
    
    /// <summary>
    /// Opening time for this day.
    /// </summary>
    public TimeSpan OpenTime { get; private set; }
    
    /// <summary>
    /// Closing time for this day.
    /// </summary>
    public TimeSpan CloseTime { get; private set; }

    /// <summary>
    /// Indicates if the restaurant is closed all day.
    /// Computed property based on OpenTime and CloseTime. If both are equal, it means the restaurant is closed for the entire day.. It should not be stored in the database, but calculated at runtime.
    /// </summary>
    public bool IsClosed => OpenTime == CloseTime;
    
    /// <summary>
    /// Protected constructor for EF Core.
    /// </summary>
    /// <remarks>
    /// EF CORE REQUIREMENT: Parameterless constructor needed for entity materialization from database.
    /// Properties will be set via reflection after instance creation.
    /// </remarks>
    protected BusinessHours() { }
    
    /// <summary>
    /// Creates new business hours for a specific day.
    /// </summary>
    /// <param name="restaurantId">The ID of the parent restaurant.</param>
    /// <param name="dayOfWeek">The day of the week.</param>
    /// <param name="openTime">Opening time.</param>
    /// <param name="closeTime">Closing time.</param>
    /// <remarks>
    /// AGGREGATE CREATION: This constructor should only be called by the Restaurant aggregate root
    /// through methods like SetBusinessHours(). Direct instantiation should be avoided to maintain
    /// aggregate boundary integrity.
    /// </remarks>
    public BusinessHours(int restaurantId, DayOfWeek dayOfWeek, TimeSpan openTime, TimeSpan closeTime)
    {
        if (restaurantId <= 0)
            throw new ArgumentException("RestaurantId must be greater than zero.", nameof(restaurantId));
            
        if (closeTime <= openTime)
            throw new ArgumentException("Close time must be after open time.");
        
        if (openTime < TimeSpan.Zero || openTime >= TimeSpan.FromHours(24))
            throw new ArgumentException("Open time must be between 00:00 and 23:59.", nameof(openTime));
        
        if (closeTime < TimeSpan.Zero || closeTime > TimeSpan.FromHours(24))
            throw new ArgumentException("Close time must be between 00:00 and 24:00.", nameof(closeTime));
        
        RestaurantId = restaurantId;
        DayOfWeek = dayOfWeek;
        OpenTime = openTime;
        CloseTime = closeTime;
    }
    
    /// <summary>
    /// Checks if a given time falls within business hours.
    /// </summary>
    public bool IsWithinHours(TimeSpan time)
    {
        if (IsClosed)
            return false;
        
        return time >= OpenTime && time < CloseTime;
    }
    
    /// <summary>
    /// Gets the duration of business hours for this day.
    /// </summary>
    public TimeSpan Duration => CloseTime - OpenTime;
    
    /// <summary>
    /// Returns a formatted string representation of the business hours.
    /// </summary>
    public override string ToString()
    {
        if (IsClosed)
            return $"{DayOfWeek}: Closed";
        
        return $"{DayOfWeek}: {OpenTime:hh\\:mm} - {CloseTime:hh\\:mm}";
    }
}
