<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cd4b0bb5-8990-48ff-b45d-ca7a29612a11</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BuildWebCompiler" Version="1.12.405" />
    <PackageReference Include="Markdig" Version="0.41.3" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.10.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="MudBlazor" Version="8.9.0" />
    <PackageReference Include="Polly" Version="8.6.3" />
    <PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartMenuOptim.Application\SmartMenuOptim.Application.csproj" />
    <ProjectReference Include="..\SmartMenuOptim.Infrastructure\SmartMenuOptim.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Interfaces\" />
  </ItemGroup>

</Project>
