@SmartMenuOptim.API_HostAddress = https://localhost:44388

GET {{SmartMenuOptim.API_HostAddress}}/api/Reviews
Accept: application/json

###

GET {{SmartMenuOptim.API_HostAddress}}/api/Reviews/1
Accept: application/json

