using SmartMenuOptim.Domain.Common;

namespace SmartMenuOptim.Domain.Aggregates.MenuAggregate.Events;

/// <summary>
/// Domain event raised when a dish is removed from a restaurant's menu.
/// </summary>
/// <remarks>
/// <para><strong>Event Trigger:</strong></para>
/// <para>This event is raised by the Menu aggregate when a dish is removed from the menu,
/// either temporarily (seasonal end) or permanently (discontinued).</para>
/// 
/// <para><strong>Typical Event Handlers:</strong></para>
/// <list type="bullet">
///     <item><description><strong>SearchIndexHandler:</strong> Removes dish from search indexes</description></item>
///     <item><description><strong>InventoryHandler:</strong> Adjusts ingredient ordering forecasts</description></item>
///     <item><description><strong>OrderValidationHandler:</strong> Prevents new orders containing this dish</description></item>
///     <item><description><strong>CacheHandler:</strong> Invalidates menu caches to reflect changes</description></item>
///     <item><description><strong>AnalyticsHandler:</strong> Archives dish performance data</description></item>
///     <item><description><strong>AIRecommendationHandler:</strong> Updates AI model to exclude removed dish</description></item>
///     <item><description><strong>NotificationHandler:</strong> Notifies staff of menu change</description></item>
/// </list>
/// 
/// <para><strong>Removal Reasons:</strong></para>
/// <list type="bullet">
///     <item><description><strong>Discontinued:</strong> Permanently removed from offerings</description></item>
///     <item><description><strong>SeasonalEnd:</strong> Seasonal item no longer available</description></item>
///     <item><description><strong>OutOfStock:</strong> Temporarily unavailable due to ingredient shortage</description></item>
///     <item><description><strong>Underperforming:</strong> Removed due to poor sales performance</description></item>
///     <item><description><strong>MenuRedesign:</strong> Removed as part of menu restructuring</description></item>
///     <item><description><strong>QualityIssue:</strong> Removed due to quality concerns</description></item>
///     <item><description><strong>PricingIssue:</strong> Removed for repricing/cost adjustments</description></item>
/// </list>
/// 
/// <para><strong>Business Rules:</strong></para>
/// <list type="bullet">
///     <item><description>Pending orders with this dish should be handled (notify kitchen/customer)</description></item>
///     <item><description>Dish data is preserved for historical reporting</description></item>
///     <item><description>Removal reason is required for analytics and auditing</description></item>
/// </list>
/// 
/// <para><strong>Performance Analytics Connection:</strong></para>
/// <para>When a dish is removed due to underperformance, this event can trigger archival of
/// performance metrics and AI analysis of why the dish underperformed (pricing, ingredients,
/// seasonality, customer reviews, etc.).</para>
/// </remarks>
public sealed class DishRemovedFromMenuEvent : DomainEventBase
{
    /// <summary>
    /// Gets the unique identifier of the menu.
    /// </summary>
    public int MenuId { get; init; }

    /// <summary>
    /// Gets the unique identifier of the dish being removed.
    /// </summary>
    public int DishId { get; init; }

    /// <summary>
    /// Gets the restaurant (tenant) identifier.
    /// </summary>
    public int RestaurantId { get; init; }

    /// <summary>
    /// Gets the name of the dish being removed.
    /// </summary>
    public string DishName { get; init; } = string.Empty;

    /// <summary>
    /// Gets the menu name the dish was removed from.
    /// </summary>
    public string MenuName { get; init; } = string.Empty;

    /// <summary>
    /// Gets the reason for removing the dish.
    /// </summary>
    public DishRemovalReason RemovalReason { get; init; }

    /// <summary>
    /// Gets additional notes about the removal.
    /// </summary>
    public string? RemovalNotes { get; init; }

    /// <summary>
    /// Gets whether this is a permanent removal or temporary.
    /// </summary>
    public bool IsPermanent { get; init; }

    /// <summary>
    /// Gets the expected return date for temporary removals.
    /// </summary>
    public DateTime? ExpectedReturnDate { get; init; }

    /// <summary>
    /// Gets the last price of the dish before removal.
    /// </summary>
    public decimal LastPrice { get; init; }

    /// <summary>
    /// Gets the total quantity sold during the dish's lifetime on this menu.
    /// </summary>
    public int TotalQuantitySold { get; init; }

    /// <summary>
    /// Gets the total revenue generated by this dish.
    /// </summary>
    public decimal TotalRevenue { get; init; }

    /// <summary>
    /// Gets the average rating of the dish (if reviews were collected).
    /// </summary>
    public decimal? AverageRating { get; init; }

    /// <summary>
    /// Gets the date when the dish was originally added to the menu.
    /// </summary>
    public DateTime? OriginalAddedDate { get; init; }

    /// <summary>
    /// Gets the number of days the dish was on the menu.
    /// </summary>
    public int DaysOnMenu { get; init; }

    /// <summary>
    /// Gets the staff member ID who removed the dish.
    /// </summary>
    public int? RemovedByStaffId { get; init; }

    /// <summary>
    /// Gets the category the dish belonged to.
    /// </summary>
    public string CategoryName { get; init; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="DishRemovedFromMenuEvent"/> class.
    /// </summary>
    public DishRemovedFromMenuEvent(
        int menuId,
        int dishId,
        int restaurantId,
        string dishName,
        string menuName,
        DishRemovalReason removalReason,
        bool isPermanent,
        decimal lastPrice,
        string categoryName,
        string? removalNotes = null,
        DateTime? expectedReturnDate = null,
        int totalQuantitySold = 0,
        decimal totalRevenue = 0,
        decimal? averageRating = null,
        DateTime? originalAddedDate = null,
        int daysOnMenu = 0,
        int? removedByStaffId = null)
    {
        MenuId = menuId;
        DishId = dishId;
        RestaurantId = restaurantId;
        DishName = dishName;
        MenuName = menuName;
        RemovalReason = removalReason;
        RemovalNotes = removalNotes;
        IsPermanent = isPermanent;
        ExpectedReturnDate = expectedReturnDate;
        LastPrice = lastPrice;
        CategoryName = categoryName;
        TotalQuantitySold = totalQuantitySold;
        TotalRevenue = totalRevenue;
        AverageRating = averageRating;
        OriginalAddedDate = originalAddedDate;
        DaysOnMenu = daysOnMenu;
        RemovedByStaffId = removedByStaffId;
    }

    /// <summary>
    /// Private parameterless constructor for serialization support.
    /// </summary>
    private DishRemovedFromMenuEvent() { }
}

/// <summary>
/// Defines the reason for removing a dish from the menu.
/// </summary>
public enum DishRemovalReason
{
    /// <summary>Dish is permanently discontinued.</summary>
    Discontinued = 0,

    /// <summary>Seasonal item's availability period ended.</summary>
    SeasonalEnd = 1,

    /// <summary>Temporarily unavailable due to ingredient shortage.</summary>
    OutOfStock = 2,

    /// <summary>Removed due to poor sales performance.</summary>
    Underperforming = 3,

    /// <summary>Removed as part of menu restructuring/redesign.</summary>
    MenuRedesign = 4,

    /// <summary>Removed due to quality concerns.</summary>
    QualityIssue = 5,

    /// <summary>Removed for repricing or cost adjustment.</summary>
    PricingIssue = 6,

    /// <summary>Removed due to supplier discontinuation.</summary>
    SupplierIssue = 7,

    /// <summary>Removed due to negative customer feedback.</summary>
    CustomerFeedback = 8,

    /// <summary>Removed for health/safety compliance.</summary>
    ComplianceIssue = 9,

    /// <summary>Other reason (see RemovalNotes for details).</summary>
    Other = 99
}
