/*
 * File: ProblemDetailsResponseDto.cs
 * DTO for deserializing RFC 7807 ProblemDetails responses
 * Version: 1.1
 * .NET Target: .NET 9
 * 
 * Purpose: Represents the standard RFC 7807 ProblemDetails format
 * returned by APIs when domain exceptions occur.
 */

namespace SmartMenuOptim.Server.Models.Api;

/// <summary>
/// DTO for deserializing RFC 7807 ProblemDetails responses from the API.
/// </summary>
/// <remarks>
/// This is a specific DTO for API error parsing, not to be confused
/// with generic result patterns like <see cref="Common.ClientResult{T}"/>.
/// </remarks>
public sealed record ProblemDetailsResponseDto
{
    /// <summary>
    /// A URI reference that identifies the problem type.
    /// </summary>
    public string? Type { get; init; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public string? Title { get; init; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string? Detail { get; init; }

    /// <summary>
    /// The HTTP status code generated by the origin server.
    /// </summary>
    public int? Status { get; init; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    public string? Instance { get; init; }

    /// <summary>
    /// Additional properties including error codes.
    /// </summary>
    public Dictionary<string, object?>? Extensions { get; init; }
}
