using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SmartMenuOptim.Application.Dtos
{
    /// <summary>
    /// Represents an AI-generated insight or recommendation response from the menu optimization system.
    /// </summary>
    /// <remarks>
    /// <para><strong>Purpose:</strong></para>
    /// <para>This is a Data Transfer Object (DTO) used to encapsulate AI/ML-generated recommendations
    /// for menu optimization, dish suggestions, pricing strategies, or operational improvements.</para>
    /// 
    /// <para><strong>Design Note:</strong></para>
    /// <para>This is NOT a domain entity in the DDD sense. It's a response/DTO object used for
    /// data transfer between application layers (e.g., from AI services to API controllers).
    /// It does not have identity, lifecycle, or business logic like domain entities.</para>
    /// 
    /// <para><strong>Usage Context:</strong></para>
    /// <list type="bullet">
    ///   <item><description>AI/ML service responses for menu analysis</description></item>
    ///   <item><description>Recommendation engine outputs</description></item>
    ///   <item><description>Data analytics insights</description></item>
    ///   <item><description>Dashboard insights and suggestions</description></item>
    /// </list>
    /// 
    /// <para><strong>Example Usage:</strong></para>
    /// <code>
    /// var insight = new InsightResponse
    /// {
    ///     ConfidenceScore = 0.85,  // 85% confidence
    ///     Recommendation = "Consider adding more vegetarian options during lunch hours"
    /// };
    /// 
    /// if (insight.ConfidenceScore >= 0.7)
    /// {
    ///     // High confidence - present to user
    ///     DisplayRecommendation(insight.Recommendation);
    /// }
    /// </code>
    /// 
    /// <para><strong>Future Considerations:</strong></para>
    /// <para>Consider moving this class to a dedicated DTOs or Responses namespace/folder
    /// (e.g., SmartMenuOptim.Domain.DTOs or SmartMenuOptim.Shared.Responses) to better
    /// separate DTOs from true domain entities.</para>
    /// </remarks>
    public class InsightResponseDTO
    {
        /// <summary>
        /// Gets or sets the confidence score indicating how reliable the recommendation is.
        /// </summary>
        /// <remarks>
        /// <para>Represents the AI/ML model's confidence in the recommendation.</para>
        /// <para>Valid range: 0.0 (no confidence) to 1.0 (maximum confidence).</para>
        /// <para>Typical interpretation:</para>
        /// <list type="bullet">
        ///   <item><description>0.9 - 1.0: Very high confidence - strongly recommended</description></item>
        ///   <item><description>0.7 - 0.89: High confidence - recommended</description></item>
        ///   <item><description>0.5 - 0.69: Moderate confidence - consider with caution</description></item>
        ///   <item><description>Below 0.5: Low confidence - needs human review</description></item>
        /// </list>
        /// </remarks>
        [Range(0.0, 1.0, ErrorMessage = "Confidence score must be between 0.0 and 1.0")]
        public double ConfidenceScore { get; set; }

        /// <summary>
        /// Gets or sets the recommendation text generated by the AI/ML system.
        /// </summary>
        /// <remarks>
        /// <para>Human-readable recommendation or insight for restaurant operations.</para>
        /// <para>Should be clear, actionable, and specific.</para>
        /// 
        /// <para><strong>Examples:</strong></para>
        /// <list type="bullet">
        ///   <item><description>"Add 2-3 gluten-free pasta options to increase lunch revenue by estimated 15%"</description></item>
        ///   <item><description>"Reduce portion size of 'Caesar Salad' by 10% - current waste rate is 23%"</description></item>
        ///   <item><description>"Introduce happy hour pricing (3-5 PM) to increase weekday dinner reservations"</description></item>
        ///   <item><description>"Popular dish 'Margherita Pizza' is frequently out of stock - increase daily prep by 30%"</description></item>
        /// </list>
        /// </remarks>
        [Required(ErrorMessage = "Recommendation text is required")]
        [MinLength(10, ErrorMessage = "Recommendation must be at least 10 characters long")]
        [MaxLength(1000, ErrorMessage = "Recommendation cannot exceed 1000 characters")]
        public required string Recommendation { get; set; }
    }
}



